# Generated by Django 5.1.4 on 2024-12-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='pexels-cesarperez209-733745.jpg', null=True, upload_to=''),
        ),
    ]
