# Generated by Django 5.1.4 on 2024-12-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_tag_project_vote_ratio_project_vote_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='myapp.tag'),
        ),
    ]
