# Generated by Django 5.1.4 on 2024-12-30 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_project_owner'),
        ('userapp', '0003_profile_location_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.profile'),
        ),
    ]
