# Generated by Django 5.1.4 on 2024-12-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_review_owner'),
        ('userapp', '0003_profile_location_skills'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('owner', 'project')},
        ),
    ]
