# Generated by Django 5.1.4 on 2025-08-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_project_options_alter_project_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='ilya-pavlov-OqtafYT5kTw-unsplash.jpg', null=True, upload_to=''),
        ),
    ]
