# Generated by Django 5.1.4 on 2025-08-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='mateo-nCU4yq5xDEQ-unsplash.jpg', null=True, upload_to=''),
        ),
    ]
