# Generated by Django 5.1.4 on 2025-08-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_profile_options_alter_message_recepient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='hesam-link-NnOcGQhD48w-unsplash.jpg', null=True, upload_to='profiles/'),
        ),
    ]
