# Generated by Django 5.1.4 on 2025-08-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='ali-mammadli-ngAuVVO1lQ4-unsplash.jpg', null=True, upload_to='profiles/'),
        ),
    ]
